### ISSUE TITLE
I use angular18, but I do not know which ngx-flow version can I use in the angular18.

### ISSUE THREAD

**Issue by vikenpateltyler** [flowjs/ngx-flow#120] opened 2024-08-27 10:04 UTC
I use angular18, but I do not know which ngx-flow version can I use in the angular18.

**Comment by Quentigus** [comment] 2024-10-16 14:30
Hi,
There is no version compatible with Angular 18 yet.

**Comment by sebastiencl** [comment] 2024-10-23 12:48
Possible to add a version compatible with Angular 18 ? We need it. We're stuck on v17 actually.

**Comment by MaewenPelletier** [comment] 2024-10-23 12:50
Hello ! We also need to upgrade it please

**Comment by Quentigus** [comment] 2024-10-24 14:38
I juste started the migration

**Comment by sebastiencl** [comment] 2024-10-25 07:00
I tried to do it myself but it was impossible to push my branch (403)

**Comment by Quentigus** [comment] 2024-10-25 08:27
migration is done inside my branch `angular-update-18`, Il'l make the PR soon

**Comment by sebastiencl** [comment] 2024-10-31 13:17
Where is the PR? We need it on one of our projects. I can review it if needed.

**Comment by Quentigus** [comment] 2024-10-31 15:27
I didn't have time to finish.
PR is available here #122

**Comment by MaewenPelletier** [comment] 2024-10-31 15:38
Awesome thanks

**Comment by sebastiencl** [comment] 2024-10-31 15:40
Thanks

**Comment by Quentigus** [comment] 2024-10-31 15:52
PR merged to master but I don't have rights to build and publish :(

**Comment by evilaliv3** [comment] 2024-10-31 16:19
@Quentigus : do you remember who published the previous release? it was me ?

Do you confirm all works now on angular 18?

**Comment by evilaliv3** [comment] 2024-10-31 16:44
Published.

Would you please try if release 18.0.1 works on your projects?

**Comment by evilaliv3** [comment] 2024-10-31 17:48
@Quentigus : i think something could be working incorrectly. 

I'm testing it withing globaleaks and files don't get uploaded correctly).
I think we probably need some verifications on files that are uploaded to verify that the uploaded file correspond to the original file.

**Comment by Quentigus** [comment] 2024-11-01 00:00
@evilaliv3 what's the problem? is this a bug brought by the version or a historical bug?

18.0.1 is working fine inside my testing application.

**Comment by evilaliv3** [comment] 2024-11-01 07:53
I tried to upload a file of 100 mb but when downloading it it was corrupted.

Can you also make similar attempt?

My chunk size in the app is 1mb.

**Comment by evilaliv3** [comment] 2024-11-05 07:36
@Quentigus : i really think something is wrong with the patch, i retested again and i confirm that i get files loaded incorrectly mixing chunks.

When possible would you please give it a try?

**Comment by Quentigus** [comment] 2024-11-05 07:48
The migration had no impact on the code.

@evilaliv3 What version of @flowjs/flow.js is used to upload ?

I'll try to check as soon as possible

**Comment by evilaliv3** [comment] 2024-11-05 08:02
> The migration had no impact on the code.
> 
I see, maybe the new code loading differently in my setup just discloses a race condition...
In our backend we do not consider the order of chunks because we consider them to arrive in order and one by one. We need this because we encrypt the stream without writing the data in plaintext on the disk.

> @evilaliv3 What version of @flowjs/flow.js is used to upload ?

2.14.1
> 
> I'll try to check as soon as possible
Thank you!

**Comment by evilaliv3** [comment] 2024-11-05 08:11
@Quentigus actually i found the root of the cause, probably really the new code package is disclosing a regression on our codebase. No worry to retest at the moment. Thank you

**Comment by sebastiencl** [comment] 2024-11-05 08:59
I have no issue with my file uploads with the last version.

**Comment by Quentigus** [comment] 2024-11-07 13:28
I have just carried out some tests, chunks are always sent in the correct order.

Do you still get the error with "simultaneousUploads" set to "1" ?

**Comment by AidasK** [comment] 2024-11-07 13:36
You probably must set simultaneousUploads to 1 if you want to receive uploads in the correct order. This is because network/server/client/ips stuff can interfere with any request and order is not guaranteed.

**Closed** 2024-11-07 19:04 UTC
